.TH "md__r_e_a_d_m_e" 3 "Mon Jun 3 2019" "Version 0.1" "AT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_eAt 
 \- 
.SS "Members"
.PP
.IP "\(bu" 2
15/0032552 | \fCClaudio Segala Rodrigues Silva Filho\fP
.IP "\(bu" 2
00/0000000 | [Cristiano Cardoso]()
.IP "\(bu" 2
15/0137885 | \fCLuís Eduardo Luz Silva\fP
.IP "\(bu" 2
14/0033599 | [Yan Victor]() 
.PP

